### PR TITLE
Fix demo build

### PR DESCRIPTION
**Pull request by hrj**
The demo wasn't building, because of my previous changes to some APIs.

I didn't notice this earlier, because `mvn package` wasn't complaining. Only after I did a `mvn clean` followed by `mvn package` I noticed this problem.

### CODE REVIEW

**Comment by danfickle** [comment]
I think we did this at the same time! My master should now build without errors, at least it does so in Eclipse.

**Comment by hrj** [comment]
Ah ok! The diff in this PR is now reduced. The only remaining change is in the experimental package. Merging this PR will fix that too.

Aside, how do you load this project into Eclipse? Do we need to set it up manually, or is there a maven command to do it automatically? I am not very familiar with maven.

**Comment by danfickle** [comment]
mvn eclipse:eclipse

To generate Eclipse project, then file -> import existing project in Eclipse. I'll merge now. Don't worry too much about the experimental sub-project as I now think individual swing controls are the wrong way to go.

**Comment by hrj** [comment]
I hadn't looked closely at the experimental package, but when you mention "individual swing controls" I just remembered my own thoughts about it. The advantage I see is easier implementations for text selection and hover effects. But not sure how difficult it would be as a whole.

Curious to hear your thoughts.

**Comment by danfickle** [comment]
The upstream did have selection highlighting implemented for Swing. I commented it out because it was heavily dependent on the XML parser. However it should be doable to reimplement.

Have a look at
https://github.com/danfickle/flyingsaucer/blob/master/flying-saucer-core/src/main/java/org/xhtmlrenderer/swing/SelectionHighlighter.java

**Comment by hrj** [comment]
That's nice. I will create a separate issue for selection highlighting.

Also, thanks for the maven tip. Works great!

**Pull request merged**
