### PR TITLE
[Tentative] Use W3C DOM

### PR DESCRIPTION
**Pull request by hrj**
This branch uses the w3c DOM. The JSoup DOM is converted to w3c DOM during parsing. After that, there is no reference to JSoup.

Consider this experimental, though everything works fine in my simple tests.

Sharing to get feedback from you.

### CODE REVIEW

**Comment by danfickle** [comment]
Sorry about the delay. Is this code still working alright for you? I've got no objections to merging if you're happy with it.

**Comment by hrj** [comment]
Yes, it was working fine with Swing. Haven't tested the pdf module. I suggest you try some tests of your own before merging.

Switching to w3c DOM helped, but I hit some roadblocks. Turns out that most javascript libraries expect a little more than w3c DOM (the WhatWG living standards). So I am investigating an alternative path towards my goal.

Might return to flying saucer if that path doesn't work out.

**Comment by danfickle** [comment]
I'll let you in on a secret. For over two years I have been working off and on my c++ to Java convertor with the end goal of converting WebKit as a  prototype Java web browser. It sounds like you've gotten a lot closer than I have!

Also, if you haven't seen it check out the Lobo browser as an incomplete example of a Java web browser.

**Comment by hrj** [comment]
Heh, that's interesting! My first thought was also to recompile WebKit to Java bytecode. But I gave up the idea as WebKit would carry a lot of extra baggage, and that wouldn't align with my goals.

I am indeed checking out Lobo source code as part of the alternative I mentioned.

Btw, are you still interested in working on a Java browser? If so, we could chat over email.

**Comment by danfickle** [comment]
Sure, get my gmail address by running git log.

**Comment by danfickle** [comment]
I think I owe you an apology, so big SORRY. My (admittedly small) mind didn't get the gist of your argument until I split out the default user agent and realized you were right, that the core shouldn't depend on Jsoup directly. Now another parser can be used (if required) and the core has one less dependency. Anyway, I have manually merged your pull request and about to push. Thanks for the work involved also.

Daniel.

**Comment by hrj** [comment]
Oh, no worries. I am glad I was able to help in some way. This project seems to be on a roll with all the awesome work you are doing. Good luck!

**Pull request closed without merging**
